services:
  postgres-db:
    image: postgres:15
    container_name: db_reserva
    environment:
      - POSTGRES_USER=usuario_dev
      - POSTGRES_PASSWORD=password_pro
      - POSTGRES_DB=reserva-salas-coworking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: