spring.application.name=reserva-salas-coworking
# ==========================================
# CONEXIÓN A LA BASE DE DATOS (DOCKER)
# ==========================================

# La URL de conexión: 
# localhost:5432 es la "dirección" de tu contenedor en Windows.
# /nexus_admissions es el nombre de la DB que definiste en tu docker-compose.
spring.datasource.url=jdbc:postgresql://localhost:5432/reserva-salas-coworking

# El usuario que configuraste en el entorno de Docker (POSTGRES_USER)
spring.datasource.username=usuario_dev

# La contraseña que configuraste en el entorno de Docker (POSTGRES_PASSWORD)
spring.datasource.password=password_pro


# =========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================

# 'update' hace que Spring Boot cree o modifique las tablas en Docker 
# automáticamente basado en tus clases @Entity. ¡Súper útil en desarrollo!

spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de VS Code todas las sentencias SQL que Spring ejecute.
spring.jpa.show-sql=true

# Le dice a Hibernate que use el "lenguaje" específico de PostgreSQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# LOGS Y MONITOREO (MODO DETECTIVE)
# ==========================================

# Muestra detalles técnicos de las consultas SQL para depurar errores.
logging.level.org.hibernate.SQL=DEBUG

# Muestra los valores reales (nombres, ID, etc.) que se están guardando en las tablas.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# Cambia la ruta del Swagger visual si quieres algo m�s corto
springdoc.swagger-ui.path=/swagger
# Ruta donde Postman ir� a buscar el JSON
s

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-json
springdoc.swagger-ui.enabled=true